package pathak.creations.sbl.data_class

data class RetailerData(
    var address: String = "",
    var areaname: String = "",
    var beatname: String = "",
    var ca: String = "",
    var cac: String = "",
    var classification: String = "",
    var client: String = "",
    var country: String = "",
    var cperson: String = "",
    var cst: String = "",
    var cst_registerationdate: String = "",
    var csttin: String = "",
    var date: String = "",
    var dist_id: String = "",
    var distributor: String = "",
    var dvisit: String = "",
    var email: String = "",
    var empname: String = "",
    var firstname: String = "",
    var gstin: String = "",
    var id: String = "",
    var lastname: String = "",
    var latitude: String = "",
    var longitude: String = "",
    var mobile: String = "",
    var note: String = "",
    var pan: String = "",
    var phone: String = "",
    var pincode: String = "",
    var place: String = "",
    var retailer_id: String = "",
    var retailer_name: String = "",
    var retailer_type: String = "",
    var rid: String = "",
    var sno: String = "",
    var state: String = "",
    var type: String = "",
    var updated: String = "",
    var vattin: String = ""
)